version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - misspell

  settings:
    errcheck:
      check-type-assertions: true

issues:
  exclude-dirs:
    - internal/usecase/mocks
