// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/knjname/go-todo-api/internal/config"
	"github.com/knjname/go-todo-api/internal/repository/postgres"
	"github.com/knjname/go-todo-api/internal/usecase"
	"github.com/mazrean/kessoku"
)

func InitializeAPI(ctx context.Context) (*APIComponents, error) {
	var err error
	config0, err := kessoku.Provide(config.Load).Fn()()
	if err != nil {
		var zero *APIComponents
		return zero, err
	}
	logger := kessoku.Provide(NewLogger).Fn()()
	var err0 error
	pool, err0 := kessoku.Async(kessoku.Provide(NewPool)).Fn()(ctx, config0)
	if err0 != nil {
		var zero *APIComponents
		return zero, err0
	}
	todoRepository := kessoku.Bind[usecase.TodoRepository](kessoku.Provide(postgres.NewTodoRepository)).Fn()(pool)
	todoUseCase := kessoku.Provide(usecase.NewTodoUseCase).Fn()(todoRepository, logger)
	apicomponents := kessoku.Provide(NewAPIComponents).Fn()(config0, todoUseCase, logger, pool)
	return apicomponents, nil
}
