// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"database/sql"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/knjname/go-todo-api/internal/config"
	"github.com/knjname/go-todo-api/internal/repository/postgres"
	"github.com/knjname/go-todo-api/internal/usecase"
	"github.com/mazrean/kessoku"
	"golang.org/x/sync/errgroup"
	"log/slog"
)

func InitializeBatch(ctx context.Context) (*BatchComponents, error) {
	var (
		config0         *config.Config
		configCh        = make(chan struct{})
		logger          *slog.Logger
		loggerCh        = make(chan struct{})
		db              *sql.DB
		pool            *pgxpool.Pool
		poolCh          = make(chan struct{})
		todoRepository  *postgres.TodoRepository
		todoUseCase     *usecase.TodoUseCase
		todoUseCaseCh   = make(chan struct{})
		batchComponents *BatchComponents
	)
	eg, ctx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		select {
		case <-configCh:
		case <-ctx.Done():
			return ctx.Err()
		}
		var err error
		pool, err = kessoku.Async(kessoku.Provide(NewPool)).Fn()(ctx, config0)
		if err != nil {
			return err
		}
		close(poolCh)
		todoRepository = kessoku.Bind[usecase.TodoRepository](kessoku.Provide(postgres.NewTodoRepository)).Fn()(pool)
		select {
		case <-loggerCh:
		case <-ctx.Done():
			return ctx.Err()
		}
		todoUseCase = kessoku.Provide(usecase.NewTodoUseCase).Fn()(todoRepository, logger)
		close(todoUseCaseCh)
		return nil
	})
	var err0 error
	config0, err0 = kessoku.Provide(config.Load).Fn()()
	if err0 != nil {
		var zero *BatchComponents
		return zero, err0
	}
	close(configCh)
	logger = kessoku.Provide(NewLogger).Fn()()
	close(loggerCh)
	var err1 error
	db, err1 = kessoku.Async(kessoku.Provide(NewStdDB)).Fn()(config0)
	if err1 != nil {
		var zero *BatchComponents
		return zero, err1
	}
	for _, ch := range []<-chan struct{}{todoUseCaseCh, poolCh} {
		select {
		case <-ch:
		case <-ctx.Done():
			var zero *BatchComponents
			return zero, ctx.Err()
		}
	}
	batchComponents = kessoku.Provide(NewBatchComponents).Fn()(config0, todoUseCase, logger, pool, db)
	if err := eg.Wait(); err != nil {
		return nil, err
	}
	return batchComponents, nil
}
